package com.example.ui.utils

object Loc {
    private val strings = mapOf(
        "en" to mapOf(
            // Navigation & Tabs
            "tab_study" to "Study",
            "tab_generate" to "Generate",
            "tab_stats" to "Statistics",
            "tab_settings" to "Settings",

            // Empty state
            "empty_deck_title" to "Your Deck is Empty",
            "empty_deck_desc" to "Generate flashcards from your markdown notes or import demo decks to get started studying!",
            "btn_generate_cards" to "Generate Flashcards ⚡",
            "btn_configure_settings" to "Configure API Keys ⚙️",
            "btn_initialize_demo" to "Load Demo Deck 🚀",

            // Study screen
            "title_classic" to "🃏 Classic Study",
            "title_questions" to "❓ Only Questions",
            "title_curiosities" to "💡 Curiosities & Pills",
            "swipe_hint_main" to "↑ Skip  •  ↓ Postpone",
            "swipe_hint_tf" to "  •  ← True  •  → False",
            "btn_discover_pill" to "Discover Pill",
            "btn_show_answer" to "Show Answer",
            "feedback_correct" to "CORRECT ANSWER!",
            "feedback_incorrect" to "INCORRECT ANSWER!",
            "your_answer" to "Your answer:",
            "correct_answer_is" to "Correct answer:",
            "explanation" to "Explanation:",
            "toast_skipped" to "Card skipped ⏭️",
            "toast_postponed" to "Card postponed 🔄",
            "btn_next_card" to "Next Card",

            // Settings screen
            "settings_title" to "Settings",
            "settings_desc" to "Customize the app, AI model, and GitHub integration",
            "visual_theme" to "Visual Theme",
            "language_label" to "Language / Lingua",
            "lang_en" to "English (Default)",
            "lang_it" to "Italiano",
            "github_title" to "GitHub Repository Configuration",
            "github_owner" to "GitHub Owner / Organization",
            "github_repo" to "Repository Name",
            "github_branch" to "Default Branch (e.g., main)",
            "github_token" to "Personal Access Token (PAT)",
            "folders_title" to "Source Folders (separated by comma)",
            "folders_hint" to "e.g., Appunti, Notes",
            "openrouter_title" to "OpenRouter AI Integration",
            "openrouter_key" to "OpenRouter API Key",
            "openrouter_model" to "AI Completion Model",
            "save_success" to "Settings saved successfully! 💾",
            "btn_save_settings" to "Save Configuration",
            "btn_sync_now" to "Sync Notes from GitHub",
            "sync_success" to "Notes synchronized successfully! ⚡",
            "theme_label" to "App Visual Theme",
            "theme_system" to "System Dynamic",
            "theme_light" to "Classic Light",
            "theme_dark" to "Cosmic Dark",
            "theme_amoled" to "Amoled Black",

            // Stats Screen
            "stats_title" to "Your Progress Statistics",
            "stat_total_cards" to "Total Flashcards",
            "stat_studied" to "Studied / Progress",
            "stat_streak" to "Daily Streak",
            "stat_accuracy" to "Answer Accuracy",
            "stat_record_streak" to "Record Correct Streak",
            "difficulty_easy" to "Easy Cards",
            "difficulty_medium" to "Medium Cards",
            "difficulty_hard" to "Hard Cards",
            "clear_data" to "Reset All Progress Data",
            "clear_data_confirm" to "Are you sure you want to reset all local flashcards and learning statistics?",

            // Generate Screen
            "generate_title" to "Generate Flashcards",
            "generate_source" to "Select Markdown Source File",
            "generate_amount" to "Flashcards to Generate per File",
            "generate_type" to "Generation Output Type",
            "type_multiple" to "Multiple Choice Questions",
            "type_tf" to "True / False statements",
            "btn_generate_single" to "Generate from Selected File",
            "btn_generate_massive" to "Massive Generation (All Files)",
            "generate_progress" to "Live Progress Logs",
            "scanning_files" to "Scanning Markdown files...",
            "sync_started" to "Synchronization started...",
            "syncing_msg" to "Syncing...",
            "release_sync" to "Release to sync",
            "pull_sync" to "Pull down to sync",
            "generate_new_title" to "Generate New Flashcards",
            "type_card_label" to "Card Type",
            "number_card_label" to "Number of Cards: ",
            "source_files_label" to "Markdown Source Files (.md) in Repository",
            "detected_files" to "Detected files: ",
            "scan_desc_empty" to "No .md files detected in the repository. Please make sure your GitHub credentials are correct and that there are Markdown files in 'Notes' or the repository root.",
            "select_source_file" to "Select the file to use for generation:",
            "generating_ai" to "Generating via AI in progress...",
            "init_all" to "Initialize All",
            "cancel" to "Cancel",
            "yes_init" to "Yes, Initialize",
            "massive_dialog_title" to "Massive Initialization",
            "massive_dialog_desc" to "Are you sure you want to start automatic initialization? This process will scan your note folders on GitHub and generate exactly 5 flashcards for each detected .md file using AI.\n\nThis operation may take several minutes depending on the number of files.",
            "stats_header" to "Studio Statistics",
            "correct_label" to "Correct",
            "incorrect_label" to "Incorrect",
            "streak_records_title" to "Streak & Personal Records 🏆",
            "daily_study_label" to "Daily Study",
            "day_label" to "day",
            "days_label" to "days",
            "consecutive_correct_label" to "Consecutive Correct",
            "correct_singular" to "correct",
            "correct_plural" to "correct",
            "no_stats_available" to "No Statistics Available",
            "no_stats_desc" to "Start answering flashcards in the main study screen to generate your first learning metrics!",
            "difficulty_distribution" to "Difficulty Distribution",
            "easy_label" to "Easy",
            "medium_label" to "Medium",
            "hard_label" to "Hard",
            "card_unit" to "cards",

            // Theme localizations
            "theme_0_name" to "Cool Slate",
            "theme_0_desc" to "Sleek slate with refreshing ice-blue details.",
            "theme_1_name" to "Warm Editorial",
            "theme_1_desc" to "Ivory editorial colors for active reading.",
            "theme_2_name" to "Cosmic Royal",
            "theme_2_desc" to "Deep mysterious violet with indigo tones.",
            "theme_3_name" to "Vibrant Orchid",
            "theme_3_desc" to "Energetic fuchsia highlights and soft rose gradients.",
            "theme_4_name" to "Forest Zen",
            "theme_4_desc" to "Calming deep forest pine and soothing mint.",

            // Hub Navigation cards
            "hub_generate_title" to "Generate with AI",
            "hub_generate_desc" to "Extract from Markdown notes",
            "hub_stats_title" to "Statistics",
            "hub_stats_desc" to "See your progress",
            "filter_topic_label" to "Filter by Topic",
            "filter_all" to "All",

            // Study mode selections
            "mode_classic_title" to "Classic",
            "mode_classic_desc" to "Multiple choice and traditional True/False",
            "mode_questions_title" to "Questions Only",
            "mode_questions_desc" to "Direct questions for active recall",
            "mode_curiosities_title" to "Curiosities & Pills",
            "mode_curiosities_desc" to "Fun facts and quick curiosities",
            "start_study_btn" to "START STUDY",
            "empty_deck_dashboard_msg" to "No flashcards available. Configure your repository and notes folder to start studying.",
            "init_deck_btn" to "INITIALIZE DECK",
            "configure_repository_btn" to "Configure Repository",
            "sync_started_toast" to "Sync started...",
            "syncing_dialog_title" to "Syncing...",
            "sync_result_title" to "Sync Result",
            "sync_completed_title" to "Sync Completed",

            // Settings detail items
            "default_study_mode" to "Default Study Mode",
            "mode_classic_label" to "Classic Flashcards",
            "mode_classic_detail" to "🃏 Closed-ended questions (T/F, multiple choice)",
            "mode_questions_label" to "Questions Only",
            "mode_questions_detail" to "❓ Direct questions to stimulate active recall",
            "mode_curiosities_label" to "Curiosities & Pills",
            "mode_curiosities_detail" to "💡 Historical facts and fun curiosities about the topic",
            "ai_config_title" to "AI Configuration (OpenRouter)",
            "ai_model_desc" to "Use 'google/gemini-2.5-flash-lite' as the optimal free model on OpenRouter.",
            "daily_reminder" to "Daily Reminder",
            "daily_reminder_desc" to "Receive a notification every evening at 20:00 to maintain your streak",
            "reminder_set_toast" to "Reminder set for 20:00! 🔔",
            "reminder_disabled_toast" to "Reminder disabled",
            "github_integration" to "GitHub Integration",
            "account_owner" to "Account Owner",
            "repo_name" to "Repository Name",
            "branch" to "Branch",
            "github_cards_folder" to "Flashcard Folder on GitHub",
            "note_folders" to "Note / Outline Folders",
            "note_folders_desc" to "Separated by comma (e.g., Notes, Appunti)",
            "verifying_conn" to "Verifying...",
            "verify_conn_btn" to "Verify Repository Connection",
            "local_data_mgmt" to "Local Data Management",
            "local_data_desc" to "Remove all locally stored flashcards (e.g., old file cache). This won't delete files uploaded to GitHub.",
            "clear_cache_btn" to "Clear Local Cache",
            "cache_cleared_toast" to "Local cache cleared successfully!",
            "yes_delete" to "Yes, Delete",
            "confirm_delete_title" to "Confirm Deletion",
            "confirm_delete_desc" to "Are you sure you want to delete all cards from the local database? You will need to resync from GitHub to load them again.",
            "conn_result_title" to "Connection Result",
            "conn_error_title" to "Connection Error",

            // Active session UI details
            "back_to_dashboard_cd" to "Back to Dashboard",
            "true_false_label" to "True or False",
            "multiple_choice_label" to "Multiple Choice",
            "topic_prefix" to "📚 TOPIC: ",
            "did_you_know_title" to "💡 Did you know?",
            "explanation_details_title" to "🎯 Explanation & Details",
            "ref_answer_title" to "REFERENCE ANSWER",
            "wrong_answer_title" to "WRONG ANSWER!",
            "toast_please_fill_fields" to "Please fill in all required fields!"
        ),
        "it" to mapOf(
            // Navigation & Tabs
            "tab_study" to "Studio",
            "tab_generate" to "Genera",
            "tab_stats" to "Statistiche",
            "tab_settings" to "Impostazioni",

            // Empty state
            "empty_deck_title" to "Il tuo Mazzo è Vuoto",
            "empty_deck_desc" to "Genera flashcard dai tuoi appunti Markdown su GitHub o carica un mazzo demo per iniziare a studiare!",
            "btn_generate_cards" to "Genera Flashcard ⚡",
            "btn_configure_settings" to "Configura Chiavi API ⚙️",
            "btn_initialize_demo" to "Carica Mazzo Demo 🚀",

            // Study screen
            "title_classic" to "🃏 Studio Classico",
            "title_questions" to "❓ Solo Domande",
            "title_curiosities" to "💡 Pillola Curiosità",
            "swipe_hint_main" to "↑ Salta  •  ↓ Posticipa",
            "swipe_hint_tf" to "  •  ← Vero  •  → Falso",
            "btn_discover_pill" to "Scopri la pillola",
            "btn_show_answer" to "Mostra Risposta",
            "feedback_correct" to "RISPOSTA CORRETTA!",
            "feedback_incorrect" to "RISPOSTA ERRATA!",
            "your_answer" to "La tua risposta:",
            "correct_answer_is" to "Risposta corretta:",
            "explanation" to "Spiegazione:",
            "toast_skipped" to "Card saltata ⏭️",
            "toast_postponed" to "Card posticipata 🔄",
            "btn_next_card" to "Prossima",

            // Settings screen
            "settings_title" to "Impostazioni",
            "settings_desc" to "Personalizza l'app, il modello AI e l'integrazione GitHub",
            "visual_theme" to "Tema Visivo",
            "language_label" to "Language / Lingua",
            "lang_en" to "English (Default)",
            "lang_it" to "Italiano",
            "github_title" to "Configurazione Repository GitHub",
            "github_owner" to "Owner / Organizzazione GitHub",
            "github_repo" to "Nome Repository",
            "github_branch" to "Branch Principale (es. main)",
            "github_token" to "Token di Accesso Personale (PAT)",
            "folders_title" to "Cartelle Sorgente (separate da virgola)",
            "folders_hint" to "es. Appunti, Notes",
            "openrouter_title" to "Integrazione AI OpenRouter",
            "openrouter_key" to "Chiave API OpenRouter",
            "openrouter_model" to "Modello AI per la generazione",
            "save_success" to "Impostazioni salvate con successo! 💾",
            "btn_save_settings" to "Salva Configurazione",
            "btn_sync_now" to "Sincronizza Note da GitHub",
            "sync_success" to "Note sincronizzate correttamente! ⚡",
            "theme_label" to "Tema Visivo App",
            "theme_system" to "Dinamico di Sistema",
            "theme_light" to "Classico Chiaro",
            "theme_dark" to "Cosmico Scuro",
            "theme_amoled" to "Amoled Nero",

            // Stats Screen
            "stats_title" to "Statistiche dei tuoi Progressi",
            "stat_total_cards" to "Totale Flashcard",
            "stat_studied" to "Studiate / Progresso",
            "stat_streak" to "Streak Giornaliero",
            "stat_accuracy" to "Precisione Risposte",
            "stat_record_streak" to "Record Risposte Corrette",
            "difficulty_easy" to "Card Facili",
            "difficulty_medium" to "Card Medie",
            "difficulty_hard" to "Card Difficili",
            "clear_data" to "Azzera Tutti i Dati",
            "clear_data_confirm" to "Sei sicuro di voler azzerare tutte le flashcard e le statistiche locali?",

            // Generate Screen
            "generate_title" to "Generazione Flashcard",
            "generate_source" to "Seleziona File Sorgente Markdown",
            "generate_amount" to "Flashcard da Generare per File",
            "generate_type" to "Tipo di Flashcard da Generare",
            "type_multiple" to "Scelta Multipla",
            "type_tf" to "Vero / Falso",
            "btn_generate_single" to "Genera da File Selezionato",
            "btn_generate_massive" to "Generazione Massiva (Tutti i File)",
            "generate_progress" to "Log di Progresso Live",
            "scanning_files" to "Scansione dei file Markdown...",
            "sync_started" to "Sincronizzazione avviata...",
            "syncing_msg" to "Sincronizzazione...",
            "release_sync" to "Rilascia per sincronizzare",
            "pull_sync" to "Trascina per sincronizzare",
            "generate_new_title" to "Genera Nuove Flashcard",
            "type_card_label" to "Tipo di Card",
            "number_card_label" to "Numero di Card: ",
            "source_files_label" to "File Sorgente Markdown (.md) nel Repository",
            "detected_files" to "File rilevati: ",
            "scan_desc_empty" to "Nessun file .md rilevato nel repository. Assicurati che le credenziali GitHub siano corrette e che vi siano file Markdown in 'Appunti' o nella root del repository.",
            "select_source_file" to "Seleziona il file da utilizzare per la generazione:",
            "generating_ai" to "Generazione in corso via AI...",
            "init_all" to "Inizializza Tutto",
            "cancel" to "Annulla",
            "yes_init" to "Sì, Inizializza",
            "massive_dialog_title" to "Inizializzazione Massiva",
            "massive_dialog_desc" to "Sei sicuro di voler avviare l'inizializzazione automatica? Questo processo scansionerà le tue cartelle note su GitHub e genererà esattamente 5 flashcard per ciascun file .md rilevato tramite AI.\n\nL'operazione potrebbe richiedere alcuni minuti a seconda del numero di file.",
            "stats_header" to "Statistiche Studio",
            "correct_label" to "Corrette",
            "incorrect_label" to "Errate",
            "streak_records_title" to "Streak & Record personali 🏆",
            "daily_study_label" to "Studio Giornaliero",
            "day_label" to "giorno",
            "days_label" to "giorni",
            "consecutive_correct_label" to "Consecutive Esatte",
            "correct_singular" to "esatta",
            "correct_plural" to "esatte",
            "no_stats_available" to "Nessuna statistica disponibile",
            "no_stats_desc" to "Inizia a rispondere alle flashcard nella schermata principale per generare le tue prime metriche di studio!",
            "difficulty_distribution" to "Distribuzione Difficoltà",
            "easy_label" to "Facili",
            "medium_label" to "Medie",
            "hard_label" to "Difficili",
            "card_unit" to "card",

            // Theme localizations
            "theme_0_name" to "Ardesia Fresca",
            "theme_0_desc" to "Elegante ardesia con rinfrescanti dettagli blu ghiaccio.",
            "theme_1_name" to "Editoriale Caldo",
            "theme_1_desc" to "Colori editoriali avorio per una lettura attiva.",
            "theme_2_name" to "Viola Cosmico",
            "theme_2_desc" to "Profondo e misterioso viola con toni indaco.",
            "theme_3_name" to "Orchidea Vivace",
            "theme_3_desc" to "Energici riflessi fucsia e morbide sfumature rosa.",
            "theme_4_name" to "Zen della Foresta",
            "theme_4_desc" to "Calmante pino della foresta profonda e menta lenitiva.",

            // Hub Navigation cards
            "hub_generate_title" to "Crea con AI",
            "hub_generate_desc" to "Estrai da note Markdown",
            "hub_stats_title" to "Statistiche",
            "hub_stats_desc" to "Vedi i progressi",
            "filter_topic_label" to "Filtra per Argomento",
            "filter_all" to "Tutti",

            // Study mode selections
            "mode_classic_title" to "Classica",
            "mode_classic_desc" to "Domande multiple e Vero/Falso tradizionali",
            "mode_questions_title" to "Solo Domande",
            "mode_questions_desc" to "Domande dirette per richiamo attivo",
            "mode_curiosities_title" to "Curiosità e Pillole",
            "mode_curiosities_desc" to "Fatti divertenti e curiosità rapide",
            "start_study_btn" to "INIZIA STUDIO",
            "empty_deck_dashboard_msg" to "Nessuna flashcard disponibile. Configura il tuo archivio note e le tue credenziali per iniziare lo studio.",
            "init_deck_btn" to "INIZIALIZZA DECK",
            "configure_repository_btn" to "Configura Repository",
            "sync_started_toast" to "Sincronizzazione avviata...",
            "syncing_dialog_title" to "Sincronizzazione...",
            "sync_result_title" to "Esito Sincronizzazione",
            "sync_completed_title" to "Sincronizzazione Completata",

            // Settings detail items
            "default_study_mode" to "Modalità di Studio Default",
            "mode_classic_label" to "Flashcard Classiche",
            "mode_classic_detail" to "🃏 Domande a risposta chiusa (V/F, scelta multipla)",
            "mode_questions_label" to "Solo Domande",
            "mode_questions_detail" to "❓ Domande dirette per stimolare il richiamo attivo",
            "mode_curiosities_label" to "Curiosità e Pillole",
            "mode_curiosities_detail" to "💡 Fatti storici e curiosità divertenti sull'argomento",
            "ai_config_title" to "Configurazione AI (OpenRouter)",
            "ai_model_desc" to "Usa 'google/gemini-2.5-flash-lite' come modello gratuito ottimale su OpenRouter.",
            "daily_reminder" to "Promemoria Giornaliero",
            "daily_reminder_desc" to "Ricevi una notifica ogni sera alle 20:00 per mantenere la streak",
            "reminder_set_toast" to "Promemoria impostato per le 20:00! 🔔",
            "reminder_disabled_toast" to "Promemoria disattivato",
            "github_integration" to "Integrazione GitHub",
            "account_owner" to "Account Owner",
            "repo_name" to "Repository Name",
            "branch" to "Branch",
            "github_cards_folder" to "Cartella Flashcard su GitHub",
            "note_folders" to "Cartelle Note / Appunti",
            "note_folders_desc" to "Separate da virgola (es: Appunti, note, Scrittura)",
            "verifying_conn" to "Verifica in corso...",
            "verify_conn_btn" to "Verifica Connessione Repository",
            "local_data_mgmt" to "Gestione Dati Locale",
            "local_data_desc" to "Rimuovi tutte le flashcard memorizzate localmente sul dispositivo (es. cache dei vecchi file). Questa operazione non eliminerà i file caricati su GitHub.",
            "clear_cache_btn" to "Svuota Cache Locale",
            "cache_cleared_toast" to "Cache locale svuotata con successo!",
            "yes_delete" to "Sì, Elimina",
            "confirm_delete_title" to "Conferma Eliminazione",
            "confirm_delete_desc" to "Sei sicuro di voler eliminare tutte le card dal database locale? Dovrai ripetere la sincronizzazione da GitHub per ricaricarle.",
            "conn_result_title" to "Esito Connessione",
            "conn_error_title" to "Errore di Connessione",

            // Active session UI details
            "back_to_dashboard_cd" to "Ritorna alla Dashboard",
            "true_false_label" to "Vero o Falso",
            "multiple_choice_label" to "Risposta Multipla",
            "topic_prefix" to "📚 ARGOMENTO: ",
            "did_you_know_title" to "💡 Lo sapevi che?",
            "explanation_details_title" to "🎯 Spiegazione e Dettagli",
            "ref_answer_title" to "RISPOSTA DI RIFERIMENTO",
            "wrong_answer_title" to "RISPOSTA ERRATA!",
            "toast_please_fill_fields" to "Per favore, compila tutti i campi richiesti!"
        )
    )

    fun get(key: String, lang: String): String {
        val normalizedLang = if (lang.lowercase() == "it") "it" else "en"
        return strings[normalizedLang]?.get(key) ?: strings["en"]?.get(key) ?: key
    }
}
